production:
  server: "https://feelsfeed.herokuapp.com/faye" 

#this is the address of this heroku app once you’ve deployed it, plus the `/faye` extension. 

  secret_token: "d66010626210ab7dd17e83c8b48d737dd5a398061769329498b4bfc7135d2d93"
  signature_expiration: 3600 # one day